name: Push Content to Quartz Vaults

on: push

jobs:
  update-quartz-content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "./index.md"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo "index.md check passed!"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'false'
      run: |
        echo "index.md does not exist! Please provide an index.md file - aborting"
        exit 1

    - name: Push Obsidan Content Folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.QUARTZ_REPO_PAT }}
      with:
        source_folder: './'
        destination_repo: 'metamageia/quartz-github-cicd-example'
        destination_folder: 'content'
        destination_branch: 'main'
        user_email: 'metamageia@gmail.com'
        user_name: 'Metamageia'
        commit_msg: 'Update Quartz Website Content'